  - name: Add PPAs
    apt_repository: repo=$item
    with_items:
    - ppa:wireshark-dev/stable

  - name: Install packages
    apt: pkg=$item state=present update_cache=yes
    with_items:
    - wireshark
