
- name: Ensuring Quagga config folder exist
  file:
    dest: "{{ quagga_root_dir }}/{{ item.name }}"
    state: directory
    owner: "quagga"
    mode:  0777
  with_items: '{{ quagga_bgp_configs }}'

- name: Generating Quagga Configs
  template:
    src: "./quagga.j2"
    dest: "{{ quagga_root_dir }}/{{ item.name }}/quagga{{ item.name }}.conf"
    owner: "quagga"
    mode:  0777
  with_items: '{{ quagga_bgp_configs }}'

- name: Generating Zebra Configs
  template:
    src: "./zebra.j2"
    dest: "{{ quagga_root_dir }}/{{ item.name }}/zebra{{ item.name }}.conf"
    owner: "quagga"
    mode:   0777
  with_items: '{{ quagga_bgp_configs }}'



