- name: Create json lookup file
  local_action:
    copy
      content="{{ quagga }}"
      dest="{{ item }}"
  with_items:
    - "{{ role_path }}/files/quagga.json"

- name : quagga_config | Configuring Quagga
# item is quagga config
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ quagga_root_dir }}/{{ item.name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '{{ item.mode }}'
  notify: "restart quagga"
  with_items: '{{ quagga_configs }}'

- name: Push quagga config files
  copy
    content=config_file
    dest="/var/run/quagga/r1"
  with_items:
    - "{{ role_path }}/files/quagga.json"

#- name: Remove json file
#  local_action:
#    file
#      state=absent
#      path="{{ item }}"
#  with_items:
#    - "{{ role_path }}/files/quagga.json"

