---
#
# Installs Mininet, Wireshark and the latest openflow.lua dissector plugin (Loxi version)
#    - switch_config
#
- name: Include vars
  hosts: localhost
  tasks:
  - include_vars: vars/global_vars.yml

- hosts: localhost
  remote_user: vagrant
  serial: 1
  roles:
    - common
    - mininet
    - switch_config

